# Generated by Django 4.0.5 on 2023-03-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='dayaftersowing',
            field=models.IntegerField(default=0),
        ),
    ]
