# Generated by Django 4.0.5 on 2022-10-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='crop',
            name='image',
            field=models.ImageField(upload_to='images/crops'),
        ),
    ]
