# Generated by Django 4.0.5 on 2022-12-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_user_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='area',
        ),
    ]
