# Generated by Django 4.0.5 on 2023-09-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0006_field_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='crop_name',
            field=models.CharField(default='Default', max_length=100),
        ),
        migrations.AddField(
            model_name='field',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
