# Generated by Django 4.0.5 on 2023-09-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0007_field_crop_name_field_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='days',
        ),
        migrations.AddField(
            model_name='field',
            name='cur_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='field',
            name='start_day',
            field=models.IntegerField(default=1),
        ),
    ]
