# Generated by Django 4.0.5 on 2023-09-23 17:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0008_remove_field_days_field_cur_day_field_start_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 9, 23, 17, 21, 7, 539781, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
