# Generated by Django 4.0.5 on 2023-11-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0009_field_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='coordinates',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='field',
            name='crop_name',
            field=models.CharField(default='Cotton', max_length=100),
        ),
    ]
